# Generated by Django 4.1.4 on 2022-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('desc', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('trainer', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('year', models.DecimalField(decimal_places=0, max_digits=3)),
                ('desc', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
